---
- name: Using range
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 30

  ## Define the conditions we are looking for
  rules:
    - name: Print debug
      condition: true
      ## Define the action we should take should the condition be met
      action:
        debug:
          msg: event
